import type { Metadata } from "next";
import { Afacad } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "@/providers/theme-provider";
import { SiteFooter } from "@/components/global/site-footer";
import { SiteHeader } from "@/components/global/site-header";

const outfit = Afacad({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className} antialiased`}>
        <AppThemeProvider>
          <SiteHeader />

          {children}
          <SiteFooter />
        </AppThemeProvider>
      </body>
    </html>
  );
}
