import type { Metadata } from "next";
import { Fira_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "@/providers/theme-provider";
import { SiteFooter } from "@/components/global/site-footer";
import { SiteHeader } from "@/components/global/site-header";

const lexendDeca = Montserrat({
  variable: "--font-lexendDeca",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const firaSans = Fira_Sans({
  variable: "--font-firaSans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${lexendDeca.variable} ${firaSans.variable} antialiased`}
      >
        <AppThemeProvider>
          <SiteHeader />

          {children}
          <SiteFooter />
        </AppThemeProvider>
      </body>
    </html>
  );
}
